server:
  port: 8080
  context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/spring-boot-admin
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent-output: true
#logging:
#  file: C:/Users/zcz/git/transitOA/log/log.log
#  level:
#    com.expect: info
    
custom:
  root-path: C:/Users/zcz/git/transitOA
  avatar-path: C:/Users/zcz/git/transitOA/avatar
  attachment-path: /attachment
  ueditor-path: C:/Users/zcz/git/transitOA/ueditor
 